name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.11'  
        
      - name: Install pnpm
        run: npm install -g pnpm

      - name: pnpm install packages
        working-directory: ./free-code-camp/react
        run: pnpm install

      - name: Build Packages
        working-directory: ./free-code-camp/react
        run: pnpm build